// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
with create_feed_follow as (
insert into feed_follows(id, created_at, updated_at, user_id, feed_id)
values(
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2
) returning id, created_at, updated_at, user_id, feed_id)
select
create_feed_follow.id, create_feed_follow.created_at, create_feed_follow.updated_at, create_feed_follow.user_id, create_feed_follow.feed_id,
feeds.name as feed_name,
users.name as user_name
from create_feed_follow
inner join feeds
on create_feed_follow.feed_id = feeds.id
inner join users
on create_feed_follow.user_id = users.id
`

type CreateFeedFollowParams struct {
	UserID uuid.UUID `json:"user_id"`
	FeedID uuid.UUID `json:"feed_id"`
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	FeedID    uuid.UUID `json:"feed_id"`
	FeedName  string    `json:"feed_name"`
	UserName  string    `json:"user_name"`
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.UserID, arg.FeedID)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
with get_feed_follows as (
    select id, created_at, updated_at, user_id, feed_id from feed_follows
    where feed_follows.user_id = $1
)
select get_feed_follows.id, get_feed_follows.created_at, get_feed_follows.updated_at, get_feed_follows.user_id, get_feed_follows.feed_id,
feeds.name as feed_name,
users.name as user_name
from get_feed_follows
inner join feeds
on get_feed_follows.feed_id = feeds.id
inner join users
on get_feed_follows.user_id = users.id
`

type GetFeedFollowsForUserRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	FeedID    uuid.UUID `json:"feed_id"`
	FeedName  string    `json:"feed_name"`
	UserName  string    `json:"user_name"`
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.FeedName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollow = `-- name: Unfollow :exec
delete from feed_follows
where user_id = $1 and feed_id = $2
`

type UnfollowParams struct {
	UserID uuid.UUID `json:"user_id"`
	FeedID uuid.UUID `json:"feed_id"`
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.UserID, arg.FeedID)
	return err
}
